name: Webhook

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [webhook-event]  # Esto escuchará el evento de webhook específico

jobs:
  run-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        run: yarn dev
          # Inserta aquí el comando o secuencia de comandos que deseas ejecutar
