name: Webhook

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [webhook-event]  # Esto escuchará el evento de webhook específico

jobs:
  run-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print message
        run: echo "Hello, world! This is a simple webhook."
