name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build Docker Image
        run: |
          docker build -t my-react-app .

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker tag my-react-app gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-react-app
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-react-app
