name: Webhook

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [webhook-event]  # Esto escuchará el evento de webhook específico

jobs:
  run-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build and deploy
        run: |
          yarn dev
          # Inserta aquí el comando para desplegar tu aplicación
          echo "La aplicación ha sido desplegada exitosamente."